version: "3.9"

services:
  pg_gateway:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: paymentdb
    volumes:
      - ./backend/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  gateway_api:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - pg_gateway

  gateway_dashboard:
    build: ./frontend/dashboard
    ports:
      - "3000:3000"
    depends_on:
      - gateway_api

  checkout:
    build: ./frontend/checkout
    ports:
      - "3001:3001"
    depends_on:
      - gateway_api
