spring.datasource.url=jdbc:postgresql://pg_gateway:5432/paymentdb
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8000
server.address=0.0.0.0
